import type { Config } from 'prettier'

const config: Config = {
  semi: false,
  singleQuote: true,
  jsxSingleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  objectWrap: 'preserve',
  bracketSameLine: false,
  rangeStart: 0,
  rangeEnd: Number.POSITIVE_INFINITY,
  requirePragma: false,
  insertPragma: false,
  checkIgnorePragma: false,
  proseWrap: 'preserve',
  arrowParens: 'always',
  htmlWhitespaceSensitivity: 'css',
  endOfLine: 'lf',
  quoteProps: 'as-needed',
  vueIndentScriptAndStyle: false,
  embeddedLanguageFormatting: 'auto',
  singleAttributePerLine: true,
  experimentalOperatorPosition: 'start',
  experimentalTernaries: true,
  printWidth: 100,
  plugins: [
    'prettier-plugin-sh',
    'prettier-plugin-tailwindcss',
    'prettier-plugin-packagejson',
    '@ianvs/prettier-plugin-sort-imports',
  ],
  tailwindStylesheet: './src/style/global.css',
  importOrder: [
    '<TYPES>^(node:)',
    '<TYPES>^@/(.*)$',
    '<TYPES>^@vest/(.*)$',
    '<TYPES>^[.]',
    '<TYPES>',
    '',
    '<BUILTIN_MODULES>',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/(.*)$',
    '^@vest/(.*)$',
    '',
    '^[.]',
    '',
    '^virtual:',
  ],
  importOrderSafeSideEffects: ['^virtual:'],
  importOrderParserPlugins: ['typescript', 'jsx'],
  importOrderTypeScriptVersion: '6.0.3',
  importOrderCaseSensitive: true,
  overrides: [
    {
      files: ['.env', '.env.*', '*.sh'],
      options: {
        parser: 'sh',
        indent: 2,
        binaryNextLine: true,
        switchCaseIndent: true,
        spaceRedirects: true,
        keepComments: true,
        functionNextLine: false,
      },
    },
  ],
}

export default config
